apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kratix-idp
  title: Kratix IDP (Backstage)
  description: Backstage rodando no Kind como frontend da PoC
  annotations:
    backstage.io/kubernetes-id: kratix-idp
spec:
  type: service
  lifecycle: experimental
  owner: group:default/platform-team
  system: kratix-lab
