apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kratix-gitstatestore
  title: Kratix GitStateStore (platform-git)
  description: StateStore Git onde o Kratix escreve os outputs
spec:
  type: git-repository
  owner: group:default/platform-team
  system: kratix-lab
  dependsOn: []
