apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: kratix-postgresql-request-dev
  title: Kratix - PostgreSQL Request (DEV - commit direto)
  description: >
    Gera o YAML do request do Kratix (PostgreSQL),
    commita direto no repositório de state (GitOps)
    e registra o componente no catálogo.
  tags:
    - kratix
    - postgresql
    - gitops
spec:
  owner: group:default/platform-team
  type: service

  parameters:
    - title: Identificação
      required:
        - name
        - namespace
        - env
        - teamId
      properties:
        name:
          title: Nome do recurso (Kratix/Postgres)
          type: string
          description: Ex: acme-pg
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
        namespace:
          title: Namespace do Kubernetes
          type: string
          default: default
        env:
          title: Ambiente
          type: string
          default: dev
          enum: [dev, prod]
        teamId:
          title: Team ID (owner do banco)
          type: string
          default: acme-org-team-a

    - title: Configuração do banco
      required:
        - dbName
      properties:
        dbName:
          title: Database name
          type: string
          default: postgres
        backupEnabled:
          title: Backup habilitado?
          type: boolean
          default: false

    - title: Repositório de State (GitOps)
      required:
        - repoUrl
        - targetBranch
      properties:
        repoUrl:
          title: Repo URL (kratix-state-repo)
          type: string
          description: >
            Formato Backstage:
            github.com?owner=ORG&repo=REPO
          default: github.com?owner=clecioantao&repo=kratix-state-repo
        targetBranch:
          title: Branch destino
          type: string
          default: main

  steps:
    # 1️⃣ Gera os arquivos a partir do skeleton
    - id: generate
      name: Gerar arquivos (request + catalog-info)
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          env: ${{ parameters.env }}
          teamId: ${{ parameters.teamId }}
          dbName: ${{ parameters.dbName }}
          backupEnabled: ${{ parameters.backupEnabled }}

    # 2️⃣ Commit direto (DEV)
    - id: publish
      name: Commit no repo de state (DEV)
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        branch: ${{ parameters.targetBranch }}
        sourcePath: .
        commitMessage: "feat(kratix): add postgresql request ${{ parameters.name }}"
        description: "Kratix PostgreSQL request for ${{ parameters.name }}"

    # 3️⃣ Registro no catálogo
    - id: register
      name: Registrar no Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: catalog-info.yaml

  output:
    links:
      - title: Repositório (state repo)
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Abrir no Catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
